### PR TITLE
Bump copyright year to 2021

### PR DESCRIPTION
**Pull request by stevedlawrence**

### CODE REVIEW

**Review by mbeckerle — APPROVED** [review]
+1
But don't we have to update all the copyright banners also? That's done with script I assume.

**Comment by stevedlawrence** [comment]
Yep the build script takes care of it. This updates the ``footer.html`` page, which is included as the footer of all pages. So when the build script regenerates the pages, all of their coypright years in the footer will be updated.

**Review by tuxji — APPROVED** [review]
+1

Do we also need to update the Open Grid Forum copyrights?

```
site/docs/dfdl/index.html
3080:<p class=MsoNormal>Copyright &copy; Open Grid Forum (2006-2020).&nbsp; Some
32289:<p class=MsoNormal>Copyright (C) Open Grid Forum (2005-2020). Some Rights
```

**Comment by stevedlawrence** [comment]
I'm not sure. I'm hesitent to update copyrights that come from other outside libraries/docuemnts. I think we want to keep the copyrights exactly as they were when we took them. When they update their licenses, and when we update to newer versions of libs/deps that have those licenses, then we probably do want to pull in those updates (also ensuring any license updates are compatible with Apache).

**Pull request merged**
