### PR TITLE
Update DFDL Specification to link to r35 public review HTML version

### PR DESCRIPTION
**Pull request by mbeckerle**
DAFFODIL-2442

### CODE REVIEW

**Review by tuxji — APPROVED** [review]
+1

Although the GitHub diff didn't make it obvious, I see you removed gwdrp-dfdl-v1.0.4_files, moved both gwdrp-dfdl-v1.0.5-r35.htm and gwdrp-dfdl-v1.0.5-r35_files up one level, and renamed the html file so it replaced index.html.

**Comment by stevedlawrence** [comment]
+1 with one minor comment:

I can't make an inline comment since github won't show the large diff, but part of this change removes the following in index.html:
```diff
-body {
-	max-width: 1024px;
-	margin: auto;
-}
```
I suspect this bit of CSS isn't part of the autogenerated HTML and that someone (probably me?) added it later, but I think this would be a change worth keeping. This makes it so the DFDL docs don't grow beyond a width of 1024 pixels, which can be helpful on widescreens. Ottherwise it's a bit hard to read with super long lines.

**Comment by mbeckerle** [comment]
It is an objective for this HTML to be "fully elastic" to any width. Setting widths has caused many problems with tables, etc. So removing all the style information so that everything presents at the full-width of the browser window used has actually been a goal. 

That said, I've been adding formatting related issues as public-review comments to the public review. 

The work around, which is to narrow the browser window being used, is easy enough.

This HTML version is also the public-review draft and will be replaced later with the official version once that is out, probably early in 2021. At that point we can deal with formatting considerations. There are numerous others besides this one. MS-Word is pretty bad at preserving style uniformity when creating HTML.

**Comment by mbeckerle** [comment]
https://github.com/OpenGridForum/Editor/issues/12 is the public comment about this issue.

**Pull request merged**
